### ISSUE TITLE
[Bug] 在线玩家Error occurred while contacting login servers, are they down?

### ISSUE THREAD

**Issue by angushushu** [FallenCrystal/CubeX-Log#105]
**描述**
在线账号会出现”Error occurred while contacting login servers, are they down?“无法进入。
BC log：
```
[23:04:48] [FastLogin Pool Thread #6/INFO] [FastLogin]: Handling player angushushu
[23:04:48] [FastLogin Pool Thread #6/INFO] [FastLogin]: Requesting premium login for registered player: angushushu
[23:04:55] [Netty Worker IO Thread #3/ERROR]: Error authenticating angushushu with minecraft.net
io.netty.channel.ConnectTimeoutException: connection timed out: sessionserver.mojang.com/13.107.238.49:443
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:613) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:05:46] [Netty Worker IO Thread #9/INFO]: [/222.73.141.188:62515] <-> InitialHandler has connected
```

**复现**
1. 用在线账号进服（任意线路）
3. 复现

**预期行为**
应该直接进入登录服并自动登录。如果是mojang抽风的话，隔壁服务器的正版验证好像没有问题。

**截图/媒体**
![image](https://user-images.githubusercontent.com/23127549/225947804-f256371d-e1dc-450a-90c3-8fca601697bc.png)

**附加内容**
无

**Comment by FallenCrystal** [comment]
CNAME record issue. cannot fix. caused by DNS.

**Comment by FallenCrystal** [comment]
* Dont use Netty DNS resolver.

**Comment by angushushu** [comment]
我在群里发个公告，然后去godaddy问问

**Comment by FallenCrystal** [comment]
i think you should know about TCPShield proxy.
of course. They dont have servers in china `even relatively close.

> even if not. the latency you connect to TCPShield is always greater than 500ms.  

tcpshield has 3 OVH proxy server. (Germany, France and Canada)
imagine that.

when you are crushed by an adversary because of network latency. ur connection was timed out.
then you cant join the server.
and then you refresh your server list.
*wow* various servers. pika-network, blockdrop, blocksmc all connection timeouts. `cname resolves it from the german server to the canadian server.`
and then. u can think that the end of the world is coming. or you didnt pay your internet bill. or maybe your broadband carrier tells you to plug in and unplug the network cable.
but wait until about 600 seconds `(TTL time)` have passed. those servers can be connected again.
its funny. right? but if you are one of the victims. u probably won't find it interesting anymore. `XD`

**Comment by angushushu** [comment]
huh所以是最近的那个解析服务器寄了么，那要把bc的那个连接时长调高点么？我只去wfx试了一下他们那看起来正常，不知道是不是调了连接时长还是因为服务器位置不一样。

**Comment by FallenCrystal** [comment]
> huh所以是最近的那个解析服务器寄了么.

true.

**Comment by angushushu** [comment]
供应商说是api.mojang.com被大陆防火墙限制了。
解决方案：
1. DNS代理 （供应商说可以帮忙想办法但目前没有海外机器）
2. 弃用正版验证
有什么倾向么？弃用正版验证对uuid会有影响吧。

**Comment by FallenCrystal** [comment]
> 供应商说是api.mojang.com被大陆防火墙限制了。 解决方案：
> 
> 1. DNS代理 （供应商说可以帮忙想办法但目前没有海外机器）
> 2. 弃用正版验证
>    有什么倾向么？弃用正版验证对uuid会有影响吧。

限制个毛线 而且是sessionserver.mojang.com
不是
api.mojang.com

**Comment by angushushu** [comment]
那就，静观其变？

**Comment by FallenCrystal** [comment]
> 那就，静观其变？

什么什么静观其变的 本来就这样了 啥也干不了

**Comment by angushushu** [comment]
记录一下：供应商给加了个代理，看起来是解决了
